# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oaisys.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oaisys.proto',
  package='oaisys',
  syntax='proto3',
  serialized_options=b'\n\027io.grpc.examples.oaisysB\013oaisysProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0coaisys.proto\x12\x06oaisys\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xaa\x01\n\x13SensorModuleRequest\x12\x32\n\x04pose\x18\x01 \x01(\x0b\x32$.oaisys.SensorModuleRequest.PoseType\x1a_\n\x08PoseType\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x0b\n\x03q_w\x18\x04 \x01(\x02\x12\x0b\n\x03q_x\x18\x05 \x01(\x02\x12\x0b\n\x03q_y\x18\x06 \x01(\x02\x12\x0b\n\x03q_z\x18\x07 \x01(\x02\"\x07\n\x05\x45mpty\"H\n\x0fStepSampleReply\x12\x12\n\nsuccessRet\x18\x01 \x01(\x08\x12\x0f\n\x07\x62\x61tchID\x18\x02 \x01(\x05\x12\x10\n\x08sampleID\x18\x03 \x01(\x05\"$\n\x0eStepBatchReply\x12\x12\n\nsuccessRet\x18\x01 \x01(\x08\" \n\nSuccessMsg\x12\x12\n\nsuccessRet\x18\x01 \x01(\x08\":\n\x13RenderFinishedReply\x12\r\n\x05state\x18\x01 \x01(\x05\x12\x14\n\x0c\x66ilePathList\x18\x02 \x03(\t\"+\n\x1a\x42\x61tchCreationFinishedReply\x12\r\n\x05state\x18\x01 \x01(\x05\"M\n\x11StepSampleRequest\x12\x38\n\x13sensorModuleRequest\x18\x01 \x01(\x0b\x32\x1b.oaisys.SensorModuleRequest\"\x12\n\x10StepBatchRequest2~\n\x07Greeter\x12\x36\n\x08SayHello\x12\x14.oaisys.HelloRequest\x1a\x12.oaisys.HelloReply\"\x00\x12;\n\rSayHelloAgain\x12\x14.oaisys.HelloRequest\x1a\x12.oaisys.HelloReply\"\x00\x32\xd1\x02\n\x06Oaisys\x12\x42\n\nStepSample\x12\x19.oaisys.StepSampleRequest\x1a\x17.oaisys.StepSampleReply\"\x00\x12?\n\tStepBatch\x12\x18.oaisys.StepBatchRequest\x1a\x16.oaisys.StepBatchReply\"\x00\x12>\n\x0eRenderFinished\x12\r.oaisys.Empty\x1a\x1b.oaisys.RenderFinishedReply\"\x00\x12L\n\x15\x42\x61tchCreationFinished\x12\r.oaisys.Empty\x1a\".oaisys.BatchCreationFinishedReply\"\x00\x12\x34\n\rEndSimulation\x12\r.oaisys.Empty\x1a\x12.oaisys.SuccessMsg\"\x00\x42.\n\x17io.grpc.examples.oaisysB\x0boaisysProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='oaisys.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='oaisys.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=52,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='oaisys.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='oaisys.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=83,
)


_SENSORMODULEREQUEST_POSETYPE = _descriptor.Descriptor(
  name='PoseType',
  full_name='oaisys.SensorModuleRequest.PoseType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='oaisys.SensorModuleRequest.PoseType.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='oaisys.SensorModuleRequest.PoseType.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='oaisys.SensorModuleRequest.PoseType.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q_w', full_name='oaisys.SensorModuleRequest.PoseType.q_w', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q_x', full_name='oaisys.SensorModuleRequest.PoseType.q_x', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q_y', full_name='oaisys.SensorModuleRequest.PoseType.q_y', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q_z', full_name='oaisys.SensorModuleRequest.PoseType.q_z', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=256,
)

_SENSORMODULEREQUEST = _descriptor.Descriptor(
  name='SensorModuleRequest',
  full_name='oaisys.SensorModuleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='oaisys.SensorModuleRequest.pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SENSORMODULEREQUEST_POSETYPE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=256,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='oaisys.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=265,
)


_STEPSAMPLEREPLY = _descriptor.Descriptor(
  name='StepSampleReply',
  full_name='oaisys.StepSampleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='successRet', full_name='oaisys.StepSampleReply.successRet', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batchID', full_name='oaisys.StepSampleReply.batchID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sampleID', full_name='oaisys.StepSampleReply.sampleID', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=339,
)


_STEPBATCHREPLY = _descriptor.Descriptor(
  name='StepBatchReply',
  full_name='oaisys.StepBatchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='successRet', full_name='oaisys.StepBatchReply.successRet', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=377,
)


_SUCCESSMSG = _descriptor.Descriptor(
  name='SuccessMsg',
  full_name='oaisys.SuccessMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='successRet', full_name='oaisys.SuccessMsg.successRet', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=411,
)


_RENDERFINISHEDREPLY = _descriptor.Descriptor(
  name='RenderFinishedReply',
  full_name='oaisys.RenderFinishedReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='oaisys.RenderFinishedReply.state', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filePathList', full_name='oaisys.RenderFinishedReply.filePathList', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=471,
)


_BATCHCREATIONFINISHEDREPLY = _descriptor.Descriptor(
  name='BatchCreationFinishedReply',
  full_name='oaisys.BatchCreationFinishedReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='oaisys.BatchCreationFinishedReply.state', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=516,
)


_STEPSAMPLEREQUEST = _descriptor.Descriptor(
  name='StepSampleRequest',
  full_name='oaisys.StepSampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensorModuleRequest', full_name='oaisys.StepSampleRequest.sensorModuleRequest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=518,
  serialized_end=595,
)


_STEPBATCHREQUEST = _descriptor.Descriptor(
  name='StepBatchRequest',
  full_name='oaisys.StepBatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=615,
)

_SENSORMODULEREQUEST_POSETYPE.containing_type = _SENSORMODULEREQUEST
_SENSORMODULEREQUEST.fields_by_name['pose'].message_type = _SENSORMODULEREQUEST_POSETYPE
_STEPSAMPLEREQUEST.fields_by_name['sensorModuleRequest'].message_type = _SENSORMODULEREQUEST
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['SensorModuleRequest'] = _SENSORMODULEREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['StepSampleReply'] = _STEPSAMPLEREPLY
DESCRIPTOR.message_types_by_name['StepBatchReply'] = _STEPBATCHREPLY
DESCRIPTOR.message_types_by_name['SuccessMsg'] = _SUCCESSMSG
DESCRIPTOR.message_types_by_name['RenderFinishedReply'] = _RENDERFINISHEDREPLY
DESCRIPTOR.message_types_by_name['BatchCreationFinishedReply'] = _BATCHCREATIONFINISHEDREPLY
DESCRIPTOR.message_types_by_name['StepSampleRequest'] = _STEPSAMPLEREQUEST
DESCRIPTOR.message_types_by_name['StepBatchRequest'] = _STEPBATCHREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'oaisys_pb2'
  # @@protoc_insertion_point(class_scope:oaisys.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'oaisys_pb2'
  # @@protoc_insertion_point(class_scope:oaisys.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

SensorModuleRequest = _reflection.GeneratedProtocolMessageType('SensorModuleRequest', (_message.Message,), {

  'PoseType' : _reflection.GeneratedProtocolMessageType('PoseType', (_message.Message,), {
    'DESCRIPTOR' : _SENSORMODULEREQUEST_POSETYPE,
    '__module__' : 'oaisys_pb2'
    # @@protoc_insertion_point(class_scope:oaisys.SensorModuleRequest.PoseType)
    })
  ,
  'DESCRIPTOR' : _SENSORMODULEREQUEST,
  '__module__' : 'oaisys_pb2'
  # @@protoc_insertion_point(class_scope:oaisys.SensorModuleRequest)
  })
_sym_db.RegisterMessage(SensorModuleRequest)
_sym_db.RegisterMessage(SensorModuleRequest.PoseType)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'oaisys_pb2'
  # @@protoc_insertion_point(class_scope:oaisys.Empty)
  })
_sym_db.RegisterMessage(Empty)

StepSampleReply = _reflection.GeneratedProtocolMessageType('StepSampleReply', (_message.Message,), {
  'DESCRIPTOR' : _STEPSAMPLEREPLY,
  '__module__' : 'oaisys_pb2'
  # @@protoc_insertion_point(class_scope:oaisys.StepSampleReply)
  })
_sym_db.RegisterMessage(StepSampleReply)

StepBatchReply = _reflection.GeneratedProtocolMessageType('StepBatchReply', (_message.Message,), {
  'DESCRIPTOR' : _STEPBATCHREPLY,
  '__module__' : 'oaisys_pb2'
  # @@protoc_insertion_point(class_scope:oaisys.StepBatchReply)
  })
_sym_db.RegisterMessage(StepBatchReply)

SuccessMsg = _reflection.GeneratedProtocolMessageType('SuccessMsg', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESSMSG,
  '__module__' : 'oaisys_pb2'
  # @@protoc_insertion_point(class_scope:oaisys.SuccessMsg)
  })
_sym_db.RegisterMessage(SuccessMsg)

RenderFinishedReply = _reflection.GeneratedProtocolMessageType('RenderFinishedReply', (_message.Message,), {
  'DESCRIPTOR' : _RENDERFINISHEDREPLY,
  '__module__' : 'oaisys_pb2'
  # @@protoc_insertion_point(class_scope:oaisys.RenderFinishedReply)
  })
_sym_db.RegisterMessage(RenderFinishedReply)

BatchCreationFinishedReply = _reflection.GeneratedProtocolMessageType('BatchCreationFinishedReply', (_message.Message,), {
  'DESCRIPTOR' : _BATCHCREATIONFINISHEDREPLY,
  '__module__' : 'oaisys_pb2'
  # @@protoc_insertion_point(class_scope:oaisys.BatchCreationFinishedReply)
  })
_sym_db.RegisterMessage(BatchCreationFinishedReply)

StepSampleRequest = _reflection.GeneratedProtocolMessageType('StepSampleRequest', (_message.Message,), {
  'DESCRIPTOR' : _STEPSAMPLEREQUEST,
  '__module__' : 'oaisys_pb2'
  # @@protoc_insertion_point(class_scope:oaisys.StepSampleRequest)
  })
_sym_db.RegisterMessage(StepSampleRequest)

StepBatchRequest = _reflection.GeneratedProtocolMessageType('StepBatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _STEPBATCHREQUEST,
  '__module__' : 'oaisys_pb2'
  # @@protoc_insertion_point(class_scope:oaisys.StepBatchRequest)
  })
_sym_db.RegisterMessage(StepBatchRequest)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='oaisys.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=617,
  serialized_end=743,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='oaisys.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SayHelloAgain',
    full_name='oaisys.Greeter.SayHelloAgain',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER


_OAISYS = _descriptor.ServiceDescriptor(
  name='Oaisys',
  full_name='oaisys.Oaisys',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=746,
  serialized_end=1083,
  methods=[
  _descriptor.MethodDescriptor(
    name='StepSample',
    full_name='oaisys.Oaisys.StepSample',
    index=0,
    containing_service=None,
    input_type=_STEPSAMPLEREQUEST,
    output_type=_STEPSAMPLEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StepBatch',
    full_name='oaisys.Oaisys.StepBatch',
    index=1,
    containing_service=None,
    input_type=_STEPBATCHREQUEST,
    output_type=_STEPBATCHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RenderFinished',
    full_name='oaisys.Oaisys.RenderFinished',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RENDERFINISHEDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BatchCreationFinished',
    full_name='oaisys.Oaisys.BatchCreationFinished',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_BATCHCREATIONFINISHEDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EndSimulation',
    full_name='oaisys.Oaisys.EndSimulation',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SUCCESSMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OAISYS)

DESCRIPTOR.services_by_name['Oaisys'] = _OAISYS

# @@protoc_insertion_point(module_scope)
